brand:
  name: ZeeWoo
menu-string: Menu

nav:
  - title: Introduction
    url: '#introduction'
  - title: Manual
    url: '#manual'
  - title: Download
    url: '#download'

copyright: Copyright &copy; Your Website 2018

social-buttons:
  - icon: fab fa-github
    url: '#' 

quicklinks:
  - title: Privacy Policy
    url: '#'
  - title: Terms of Use
    url: '#'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
