brand:
  name: ZeeWoo
  font:'Edu VIC WA Beginner Bold 700';
menu-string: Menu

nav:
  - title: Introduction
    url: '#survices'
  - title: Manual
    url: '#portfolio'
  - title: Download
    url: '#team'

copyright: Copyright &copy; ZeeWoo 2024

social-buttons:
  - icon: fab fa-github
  # 오픈소스 배포됨
    url: 'https://github.com/Gyuwon-Yonsei-CPSS/ZeeWoo.git' 

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
